# ==========================================================
# Hetzner Shop
# Pytest Configuration
# ==========================================================


[pytest]


# Test directory

testpaths = tests



# Async support

asyncio_mode = auto



# Output options

addopts = -v



# Python files pattern

python_files = test_*.py
